"""Initial migration

Revision ID: 342093c66ad9
Revises: 
Create Date: 2023-10-09 12:59:07.369147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '342093c66ad9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=100), nullable=False),
    sa.Column('numero_documento', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('correo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('direccion', sa.String(length=100), nullable=False),
    sa.Column('contacto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contacto_id'], ['contact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telefono',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('contacto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contacto_id'], ['contact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telefono')
    op.drop_table('correo')
    op.drop_table('contact')
    # ### end Alembic commands ###
